name: Upload Python Package

on:
  pull_request:
  push:
    branches:
    - "*"
    tags:
    - "v*"

jobs:
  test-pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pytest-ruff
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
